name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "10 5 */14 10-12,1-5 *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Build gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
          gotip version
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-
            ${{ runner.OS }}-
      - name: Get dependencies
        run: gotip get -d -t -v ./...
      - name: Build
        run: gotip run .
      - name: "Test: GOEXPERIMENT=unified"
        run: GOEXPERIMENT=unified gotip test -vet=off .
      - name: "Test: -gcflags=-G=3"
        run: gotip test -gcflags=-G=3 .
